### PR TITLE
Conan Search for v1 apis

### LINKED ISSUE #13: conan search
Implement the search endpoint https://github.com/conan-io/conan/blob/1afadb5cca9e1c688c7b37c69a0ff3c6a6dbe257/conans/server/rest/controllers/conan_controller.py#L130

### LINKED ISSUE #68: Conan search return html 404
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Do conan search of my package just after I upload it to the nexus

* **What feature or behavior is this required for?**
NA?

* **How could we solve this issue? (Not knowing is okay!)**
I don't know

* **Anything else?**
Here is the scenario, I have uploaded my package:
``` shell
$ conan upload Hello/0.1@kevin/testing -r=nxrm-conan-hosted --all

Uploading to remote 'nxrm-conan-hosted':
Uploading Hello/0.1@kevin/testing to remote 'nxrm-conan-hosted'
Uploading conanfile.py:   0%|          | 0.00/705 [00:0Uploading conanfile.py: 100%|##########| 705/705 [00:00<00:00, 663kB/s]
Uploading conanmanifest.txt:   0%|          | 0.00/58.0Uploading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 49.7kB/s]

Uploaded conan recipe 'Hello/0.1@kevin/testing' to 'nxrm-conan-hosted': http://localhost:8082/repository/conan-nexus/
Uploading package 1/1: de56269f90f07cc61427d9012acf098d4354f43d to 'nxrm-conan-hosted'
Package is up to date, upload skipped
```

But then when I am about to search it, it returns an html with 404 mentioned.

``` shell
$ conan search Hello/0.1@kevin/testing -r=nxrm-conan-hosted
ERROR:
<!DOCTYPE html>
<html lang="en">
<head>
  <title>404 - Nexus Repository Manager</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


  <!--[if lt IE 9]>
  <script>(new Image).src="http://localhost:8082/favicon.ico?3.18.1-01"</script>
  <![endif]-->
  <link rel="icon" type="image/png" href="http://localhost:8082/favicon-32x32.png?3.18.1-01" sizes="32x32">
  <link rel="mask-icon" href="http://localhost:8082/safari-pinned-tab.svg?3.18.1-01" color="#5bbad5">
  <link rel="icon" type="image/png" href="http://localhost:8082/favicon-16x16.png?3.18.1-01" sizes="16x16">
  <link rel="shortcut icon" href="http://localhost:8082/favicon.ico?3.18.1-01">
  <meta name="msapplication-TileImage" content="http://localhost:8082/mstile-144x144.png?3.18.1-01">
  <meta name="msapplication-TileColor" content="#00a300">

  <link rel="stylesheet" type="text/css" href="http://localhost:8082/static/css/nexus-content.css?3.18.1-01"/>
</head>
<body>
<div class="nexus-header">
  <a href="http://localhost:8082">
    <div class="product-logo">
      <img src="http://localhost:8082/static/images/nexus.png?3.18.1-01" alt="Product logo"/>
    </div>
    <div class="product-id">
      <div class="product-id__line-1">
        <span class="product-name">Nexus Repository Manager</span>
      </div>
      <div class="product-id__line-2">
        <span class="product-spec">OSS 3.18.1-01</span>
      </div>
    </div>
  </a>
</div>

<div class="nexus-body">
  <div class="content-header">
    <img src="http://localhost:8082/static/rapture/resources/icons/x32/exclamation.png?3.18.1-01" alt="Exclamation point" aria-role="presentation"/>
    <span class="title">Error 404</span>
    <span class="description">Not Found</span>
  </div>
  <div class="content-body">
    <div class="content-section">
      Not Found
    </div>
      </div>
</div>
</body>
</html>

. [Remote: nxrm-conan-hosted]
```

I don't know why and how can it return the 404 html.

### LINKED ISSUE #71: conan download 404
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
The "conan install <component>" works OK. Replacing it with "conan download <component>" FAILs.

* **What feature or behavior is this required for?**
The developer wants to find the latest version to package it up for delivery to a target system.

* **How could we solve this issue? (Not knowing is okay!)**
Implement the /search api - compare #13 

* **Anything else?**
Did "conan download" work at any time?

### PR DESCRIPTION
**Pull request by 1BE6-ankit**
This PR addresses the v1 hosted search endpoints for `conan search` command. 

This pull request makes the following changes:
* A new package *org.sonatype.repository.conan.internal.hosted* is added which contains the logic to handle the search requests
* Search matchers and handlers are added in _org.sonatype.repository.conan.internal.hosted.ConanHostedRecipe_ and _package org.sonatype.repository.conan.internal.hosted.HostedHandlers_
* When a user searches based on full package reference, for example: `conan search package/version@group/channel -r=conan-hosted`, we will need to read the contents of the conaninfo files for the matching binaries. There exists a protected method: _org.sonatype.repository.conan.internal.hosted.ConanHostedFacet:doGet_ for this exact case. To extend its functionality, a public wrapper _doGetPublic_ was added.
* Unit Tests for the main logical parts of the search.

It relates to the following issue #s:
* Fixes #71 
* Fixes #13 
* Fixes #68

### CODE REVIEW

**Comment by DarthHater** [comment]
@jlstephens89 wanna take a look see at this?

**Comment by yuriy-mochurad** [comment]
would be great to have this feature in master

**Comment by jheaff1** [comment]
The issue of "conan search" failing on Nexus3 hosted Conan repository is a blocks me using it at all. Looking forward to this issue being fixed in master

**Comment by 1BE6-ankit** [comment]
@jheaff1 Thanks for you comment. I am sorry but I do not completely understand your first sentence:"... blocks me using...".

**Comment by jheaff1** [comment]
@1BE6-ankit Hi, apologies for not being clear. What I meant was that I will not be using Nexus as a Conan repository for my team to use until the “conan search” issue is fixed.

I would very much like to use Nexus as a Conan repository as I use it for many other things.

**Comment by robertbaobao** [comment]
Are there any updates to allowing search on the hosted repo?

**Comment by VenoMpie** [comment]
Any update on this? Still not fixed as per comment in #13 . Really need conan to be part of our NXRM :P

**Pull request closed without merging**
