### PR TITLE
ISSUE 25: And sources TGZ support

### PR DESCRIPTION
**Pull request by jlstephens89**
Issue: https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/25

Adds support for conan_sources.tgz

### CODE REVIEW

**Comment by barrylapthorn** [comment]
Not sure if this helps but (close if not)....I tried cherry-picking this commit locally but nexus3 failed to start:

```
2018-08-21 15:31:18,803+0100 ERROR [FelixStartLevel]  *SYSTEM org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Failed transition: NEW -> STARTED
groovy.lang.MissingMethodException: No signature of method: org.sonatype.repository.conan.internal.hosted.ConanHostedRecipe.createRoute() is applicable for argument types: (org.sonatype.nexus.repository.view.Router$Builder, org.sonatype.nexus.repository.view.Route$Builder, java.lang.String, org.sonatype.repository.conan.internal.hosted.HostedHandlers$$Lambda$188/638833375) values: [org.sonatype.nexus.repository.view.Router$Builder@2f656b81, ...]
```

and

```
>>> 2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.sonatype.repository.conan.internal.hosted.ConanHostedRecipe.configure(ConanHostedRecipe.groovy:167)  <<<<
2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.sonatype.repository.conan.internal.hosted.ConanHostedRecipe$configure.callCurrent(Unknown Source)
2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
>>> 2018-08-21 15:31:18,850+0100 ERROR [FelixStartLevel]  *SYSTEM java.lang.Throwable -     at org.sonatype.repository.conan.internal.hosted.ConanHostedRecipe.apply(ConanHostedRecipe.groovy:141) <<<
```

**Comment by jlstephens89** [comment]
@barrylapthorn Fixed by 
https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/29/commits/f665543d235e735daf103c4e62052190f593a0df

**Comment by barrylapthorn** [comment]
Seems to work for me.  Thanks.

**Comment by jw3** [comment]
Fixed up the issue for my group, thanks.

Any idea when this gets merged?

**Pull request merged**
