### PR TITLE
allow anonymous

### PR DESCRIPTION
**Pull request by figroc**
enable anonymous repository access

### CODE REVIEW

**Comment by earonesty** [comment]
Shouldn't this be a UI option?

**Comment by figroc** [comment]
that's only a part of the story. you have to accept the anonymous credential when you recieve it.

**Comment by figroc** [comment]
@earonesty The `if` test changed is the mirrored logic of the `login()` method. That missing `isAnonymous()` test will block anonymous user to access the conan repository.

**Comment by figroc** [comment]
Accidentally 3-way merged with upstream. Rebased.

**Comment by igorudovika** [comment]
This change is redundant. In case of enabled Anonymous in NXRM Conan works without any login/password. If it is not possible to enable Anonymous in NXRM then activating Conan Rearer Token Realm + "conan user" command executing allows to get access to restricted Conan repositories.

**Pull request closed without merging**
